name: Deploy

env:
  version: ${{github.event.inputs.version-major}}.${{github.event.inputs.version-minor}}.${{github.event.inputs.version-patch}}${{github.event.inputs.version-metadata}}

on:
  workflow_dispatch:
    inputs:
      version-major:
        description: Define major build version
        required: true
      version-minor:
        description: Define minor build version
        required: true
      version-patch:
        description: Define patch build version
        required: true
      version-metadata:
        description: Define additional metadata for build version
        default: ''

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: ./ctmrepo-${{env.version}}
      - uses: actions/upload-artifact@v4
        with:
          name: ctmrepo-${{env.version}}
          path: | 
                ./ctmrepo-${{env.version}}/
                !./ctmrepo-${{env.version}}/.git/*
                !./ctmrepo-${{env.version}}/vendor/*
  deploy-artifacts:
    runs-on: ubuntu-latest
    needs: build-artifacts
    steps:
      - uses: actions/download-artifact@v4    
        with:
          name: ctmrepo-$ctmrepo-${{env.version}}
          path: artifacts
      - run: ls -R artifacts
      - uses: Creepios/sftp-action@v1.0.5
        with:
          host: ${{secrets.SERVER_IP}}
          username: ${{secrets.SERVER_USER}}
          password: ${{secrets.SERVER_PASSWORD}}
          port: 22
          localPath: artifacts/
          remotePath: data/

                
        