name: Deploy

env:
  version-major: 1
  version-minor: 1
  # This is here for testing locally, should default to true
  upload-artifact: 'true'
  download-artifact: 'true'

on:
  pull_request:
    types: closed
  push:

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: ./ctmrepo-${{env.version-major}}.${{env.version-minor}}
      - uses: actions/upload-artifact@v4
        with:
          name: ctmrepo-${{env.version-major}}.${{env.version-minor}}
          path: | 
                ./ctmrepo-${{env.version-major}}.${{env.version-minor}}/
                !./ctmrepo-${{env.version-major}}.${{env.version-minor}}/.git/*
                !./ctmrepo-${{env.version-major}}.${{env.version-minor}}/vendor/*
  deploy-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4    
        with:
          name: ctmrepo-${{env.version-major}}.${{env.version-minor}}
          path: artifacts
      - run: ls -R artifacts
                
        