name: Deploy

on:
  pull_request:
    types: closed
  push:

jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: /ctmrepo-${{github.run_id}}.${{github.run_number}}/
      - uses: actions/upload-artifact@v4
        with:
          name: ctmrepo-${{github.run_id}}.${{github.run_number}}
          path: | 
                ./ctmrepo-${{github.run_id}}.${{github.run_number}}/
                !./ctmrepo-${{github.run_id}}.${{github.run_number}}/.git/*
                
        